name: Anti-Casual Sync

on:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests psycopg2-binary

      - name: Run Anti-Casual Script
        env:
          PUBG_API_KEY: ${{ secrets.PUBG_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python anti_casual.py
